# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-18 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classcast_student_info',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pincode', models.IntegerField()),
                ('standard', models.IntegerField()),
                ('stream', models.CharField(max_length=15)),
                ('marks_scored_in_last_degree', models.FloatField()),
                ('total_time_spent_on_platform', models.FloatField()),
                ('active_status', models.CharField(max_length=15)),
                ('last_active', models.DateTimeField()),
                ('total_karma_points', models.FloatField()),
                ('phone_number', models.CharField(max_length=15)),
                ('DOB', models.DateField()),
            ],
            options={
                'db_table': 'classcast_student_info',
            },
        ),
    ]
